name: updatecli
on:
  release: null
  workflow_dispatch: null
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # Run every day
    - cron: "0 0 * * *"

permissions: {}

jobs:
  updatecli:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4.2.2"
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2"
      - name: "Run updatecli in dryrun"
        run: "updatecli compose diff"
        env:
          GITHUB_ACTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: "tibdex/github-app-token@v2.1.0"
        id: generate_token
        if: github.ref == 'refs/heads/main'
        with:
          app_id: ${{ secrets.LOIS_BOT_APP_ID }}
          private_key: ${{ secrets.LOIS_BOT_PRIVATE_KEY }}
      - name: "Run updatecli"
        if: github.ref == 'refs/heads/main'
        run: "updatecli compose apply"
        env:
          GITHUB_ACTOR: lois-bot
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
